insert into itbp_clms.liquor_brand (id, brand, created_by, creation_time, modified_by, modification_time)
values  (1, 'Kingfisher', null, null, null, null),
        (2, 'KingfisherPremium', null, null, null, null),
        (3, 'OldMonk', null, null, null, null),
        (4, 'OldMonktheLegendDeluxePremiumRumVeryOld', null, null, null, null),
        (5, 'Solan', null, null, null, null),
        (6, 'OldMonkMaturedXXXSelectRumVeryOldVatted', null, null, null, null),
        (7, 'Seagrams', null, null, null, null),
        (8, 'SeagramsBlendersPride', null, null, null, null),
        (9, 'SeagramsRoyalStag', null, null, null, null),
        (10, 'BacardiLimon', null, null, null, null),
        (11, 'DewarsBlendedScotchWhiskyWhiteLabel', null, null, null, null),
        (12, 'BlackbyBacardiOriginalPremiumCraftedRum', null, null, null, null),
        (13, 'BlackbyBacardiOriginalPremiumCraftedRum', null, null, null, null),
        (14, 'WilliamLawsonsBlendedScotchWhisky', null, null, null, null),
        (15, 'BejoisVSOP', null, null, null, null),
        (16, 'BejoisVSOPBlendedGrapeBrandy750ml', null, null, null, null),
        (17, 'AmrutFusionSingleMaltWhisky750ml', null, null, null, null),
        (18, 'AmrutPrestigeBlendedMaltwhisky750ml', null, null, null, null),
        (19, 'AmurutAmalgamMaltwhisky750ml', null, null, null, null),
        (20, 'AmurutAmalgamMaltwhisky750ml', null, null, null, null),
        (21, 'MaqintoshPremiumwhisky750ml', null, null, null, null),
        (22, 'AmrutsMaqintoshsilverEditionwhisky750ml', null, null, null, null);