insert into itbp_clms.log_master_entities (id, entity_id, entity_name, address, city, state, latitude, longitude, chairman, supervisor, executive, chairman_mailid, supervisor_mailid, executive_mailid, chairman_mobileno, supervisor_mobileno, executive_mobileno, authorised_distributor_entity_type_id, authorised_distributor, entity_type, created_by, creation_time, modified_by, modification_time, isactive, deactive_time, deactivated_by)
values  (1, 3, 'HAMMY', 'TEST DRIVER', '52', '3', null, null, 190, 193, 195, 'NOT@hotmail.COM', 'dassarwan.1970@hotmail.com', 'chaudharyraman88@gmail.com', null, null, null, 2, 1, 2, null, null, null, null, 1, null, null),
        (2, 4, 'CSWT Indore', 'thane', '311', '26', null, null, 35, 32, 106, 'snehal@aniruddhagps.com', 'johnsmith@gmail.com', '', null, null, null, 2, 1, 2, null, null, null, null, 1, null, null),
        (3, 25, 'KPKB SUB CANTEEN ujwal', '124 bluerose', '203', '26', null, null, 35, null, null, 'snehal@aniruddhagps.com', null, null, null, null, null, null, null, 2, null, null, null, null, 1, null, null),
        (4, 25, 'KPKB SUB CANTEEN ujwal', '124 bluerose', '193', '26', null, null, 35, null, null, 'snehal@aniruddhagps.com', null, null, null, null, null, null, null, 2, null, null, null, null, 1, null, null),
        (5, 24, 'STS BSF TIGRI NEW DELHI', 'TIGRI CAMP NEW DELHI', '223', '7', null, null, 35, 195, 204, 'snehal@aniruddhagps.com', 'chaudharyraman88@gmail.com', 'nairss68@hotmail.com', null, null, null, 2, 1, 2, null, null, null, null, 1, null, null),
        (6, 24, 'STS BSF TIGRI NEW DELHI', 'TIGRI CAMP NEW DELHI', '223', '7', null, null, 35, 195, 204, 'snehal@aniruddhagps.com', 'chaudharyraman88@gmail.com', 'nairss68@hotmail.com', null, null, null, 2, 2, 2, null, null, null, null, 1, null, null),
        (7, 24, 'STS BSF TIGRI NEW DELHI', 'TIGRI CAMP NEW DELHI', '223', '7', null, null, 35, 195, 204, 'snehal@aniruddhagps.com', 'chaudharyraman88@gmail.com', 'nairss68@hotmail.com', null, null, null, 2, 3, 2, null, null, null, null, 1, null, null),
        (8, 379, 'TEST CANTEEN', 'ADDRESS', '203', '26', null, null, 230, 232, 231, 'jitendra.pal@aniruddhagps.com', 'jitendra.pal@aniruddhagps.com', 'jitendra.pal@anirddhagps.com', null, null, null, 1, 378, 3, null, null, null, null, 1, null, null),
        (9, 380, 'TEST CANTEEN', 'mumbai', '203', '26', null, null, 230, 232, 231, 'jitendra.pal@aniruddhagps.com', 'jitendra.pal@aniruddhagps.com', 'jitendra.pal@anirddhagps.com', null, null, null, 3, 379, 2, null, null, null, null, 1, null, null),
        (10, 380, 'TEST CANTEEN', 'mumbai', '203', '26', null, null, 230, 232, 241, 'jitendra.pal@aniruddhagps.com', 'jitendra.pal@aniruddhagps.com', '', null, null, null, 3, 379, 2, null, null, null, null, 1, null, null),
        (11, 379, 'TEST Stockist', 'ADDRESS', '203', '26', null, null, 230, 232, 231, 'jitendra.pal@aniruddhagps.com', 'jitendra.pal@aniruddhagps.com', 'jitendra.pal@anirddhagps.com', null, null, null, 1, 378, 3, null, null, null, null, 1, null, null);