insert into itbp_clms.master_sub_rank (id, sub_rank, isactive)
values  (1, 'GD', null),
        (2, 'Accounts', null),
        (3, 'AT', null),
        (4, 'Civil Staff', null),
        (5, 'CM', null),
        (6, 'Edn & Stress Councellor', null),
        (7, 'EDP', null),
        (8, 'Engineering', null),
        (9, 'Follower', null),
        (12, 'Legal', null),
        (15, 'MT', null),
        (16, 'Motor Mechanic', null),
        (17, 'Office', null),
        (18, 'Para-Medic', null),
        (19, 'Para-Medical-Vet', null),
        (20, 'Pioneer', null),
        (26, 'Telecom', null),
        (27, 'Transport', null),
        (31, 'Stenographer', null),
        (32, 'Veterinary', null),
        (33, 'Printing Press', null),
        (35, 'Medical', null),
        (50, 'Llibrarian', null),
        (52, 'OL', null),
        (53, 'Tailor', null),
        (71, 'Armourer', null),
        (82, 'Workshop', null),
        (89, 'IPS', null),
        (90, 'Water Wing', null),
        (91, 'Tradesman', null);